name: tesis-env
dependencies:
  - conda
  - ipython
  - pip
  - pip:
    - -e ./cflowpost-main
    - -e ./thesis-main
variables:
  PVBATCH_BIN: "/home/ricardo/ParaView-5.9.1-MPI-Linux-Python3.8-64bit/bin/pvbatch"
